# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration (minutes)'),
        ),
    ]
