# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20170509_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='availabile end time'),
            preserve_default=False,
        ),
    ]
