# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20170511_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_capacity',
            field=models.IntegerField(default=1, verbose_name='capacity'),
        ),
    ]
