# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20170512_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='max_capacity',
        ),
    ]
