# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20170512_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
