# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import reservation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_auto_20170512_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=1, error_messages={'invalid': 'Enter a valid duration in minutes.'}, validators=[reservation.validators.validate_capacity]),
        ),
    ]
